version: "3"
services:
  nginx:
    image: website
    container_name: website
    ports:
      - 80:80
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf
      - ./website/public/:/usr/share/nginx/static/
      - ./website/dist/:/usr/share/nginx/html/
